# Please set OPENMRS_REPO_USERNAME and OPENMRS_REPO_PASSWORD variables
# for maven repo at http://mavenrepo.openmrs.org/nexus/
# as explained at https://goo.gl/SrIoyk
language: java
jdk:
 - openjdk7
 - oraclejdk7
script: 
 - if [ "$TRAVIS_JDK_VERSION" = "openjdk7" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; 
   then mvn deploy --settings maven-settings.xml;
   else mvn install;
   fi
matrix:
  allow_failures:
   jdk: oraclejdk7